xnat-web:
   build: ./tomcat
   ports:
    - "8081:8080"
   volumes:
     - ./webapps:/opt/tomcat/webapps
   links:
    - xnat-db

xnat-db:
   build: ./postgres
   expose:
     - "5432"
   volumes:
     - ./postgres-data:/var/lib/postgresql/data
